<style type="text/css">
    #newsletterForm label.error{
        position: absolute !important;
        top:100px;
        left:100px;
        color: #0000FF;
        font-size: 0.9em;
        margin-top: -5px;
        padding: 0;
        display: none;
    }

</style>
<?php
$form->setAttribute('action', $this->url('newsletter', array('action' => 'index')));
$form->setAttribute('id','newsletterForm');
$form->setAttribute('novalidate','novalidate');
$form->prepare();
echo $this->form()->openTag($form);

echo "<div class='input-group'>";
echo $this->formRow($form->get('email')->setAttribute('class','form-control')->setAttribute('label',''));
echo "<span class='input-group-btn'>";
echo $this->formSubmit($form->get('submit')->setAttribute('class','btn btn-default'));
echo "</span>";
echo "</div>";

echo $this->form()->closeTag();
?>