<div class="newsletter">
    <h4>Newsletter</h4>
    <p>Keep up on our always evolving product features and technology. Enter your e-mail and subscribe to our newsletter.</p>

    <div class="alert alert-success hidden" id="newsletterSuccess">
        <strong>Success!</strong> You've been added to our email list.
    </div>

    <div class="alert alert-danger hidden" id="newsletterError"></div>

    <form id="newsletterForm" action="php/newsletter-subscribe.php" method="POST">
        <div class="input-group">
            <input class="form-control" placeholder="Email Address" name="email" id="email" type="text">
										<span class="input-group-btn">
											<button class="btn btn-default" type="submit">Go!</button>
										</span>
        </div>
    </form>
</div>