<?php
unset($active);
$active = array();
    switch ($this->layout()->activeMenuTab){
        case 'index':
            $active['index']= 'active';
            break;
        case 'contactus':
            $active['contactus']= 'active';
            break;
        case 'portfolio':
            $active['portfolio']= 'active';
            break;
        case 'aboutus':
            $active['aboutus']= 'active';
            break;
        default:
            unset($active);
            $active['index']= 'active';
            break;
    }
?>
<header>
    <div class="container">
        <h1 class="logo">
            <a href="/">
                <img alt="Porto" src="img/logo.png">
            </a>
        </h1>
        <div class="search">
            <form id="searchForm" action="page-search-results.html" method="get">
                <div class="input-group">
                    <input type="text" class="form-control search" name="q" id="q" placeholder="Search...">
								<span class="input-group-btn">
									<button class="btn btn-default" type="button"><i class="icon icon-search"></i></button>
								</span>
                </div>
            </form>
        </div>
        <nav>
            <ul class="nav nav-pills nav-top">
                <li>
                    <a href="aboutus"><i class="icon icon-angle-right"></i>About Us</a>
                </li>
                <li>
                    <a href="contactus"><i class="icon icon-angle-right"></i>Contact Us</a>
                </li>
                <li class="phone">
                    <span><i class="icon icon-phone"></i>(425) 940-0835</span>
                </li>
            </ul>
        </nav>
        <button class="btn btn-responsive-nav btn-inverse" data-toggle="collapse" data-target=".nav-main-collapse">
            <i class="icon icon-bars"></i>
        </button>
    </div>
    <div class="navbar-collapse nav-main-collapse collapse">
        <div class="container">
            <div class="social-icons">
                <ul class="social-icons">
                    <li class="facebook"><a href="#" target="_blank" title="Facebook">Facebook</a></li>
                    <li class="twitter"><a href="https://twitter.com/JonToshmatov" target="_blank" title="Twitter">Twitter</a></li>
                    <li class="linkedin"><a href="www.linkedin.com/in/toshmatovus" target="_blank" title="Linkedin">Linkedin</a></li>
                </ul>
            </div>
            <nav class="nav-main mega-menu">
                <ul class="nav nav-pills nav-main" id="mainMenu">
                    <li class="dropdown <?php echo isset($active['index'])?$active['index']:null;?>">
                        <a class="dropdown-toggle" href="/">
                            Home
                            <i class="icon icon-angle-down"></i>
                        </a>

                    </li>
                    <li class="dropdown <?php echo isset($active['aboutus'])?$active['aboutus']:null;?>">
                        <a class="dropdown-toggle" href="aboutus">
                            About Us
                            <i class="icon icon-angle-down"></i>
                        </a>
                        <ul class="dropdown-menu">
                            <li><a href="aboutus">About Us</a></li>
                        </ul>
                    </li>
                    <li class="dropdown <?php echo isset($active['portfolio'])?$active['portfolio']:null; ?>">
                        <a class="dropdown-toggle" href="portfolio">
                            Portfolio
                            <i class="icon icon-angle-down"></i>
                        </a>
                        <ul class="dropdown-menu">
                            <li><a href="portfolio">My work samples</a></li>
                        </ul>
                    </li>
                    <li class="dropdown <?php echo isset($active['contactus'])?$active['contactus']:null;?>">
                        <a class="dropdown-toggle" href="contactus">
                            Contact Us
                            <i class="icon icon-angle-down"></i>
                        </a>
                        <ul class="dropdown-menu">
                            <li><a href="contactus">Contact Me</a></li>
                        </ul>
                    </li>
                </ul>
            </nav>
        </div>
    </div>
</header>