<?php
$title = 'About Us';
$this->headTitle($title);
?>
<div class="main" role="main">

<section class="page-top">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <ul class="breadcrumb">
                    <li><a href="index.html">Home</a></li>
                    <li class="active">About Us</li>
                </ul>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <h2>About Us</h2>
            </div>
        </div>
    </div>
</section>
<div class="container">

    <div class="row center">
        <div class="col-md-12">
            <h2 class="short word-rotator-title">The New Way to <strong data-appear-animation="bounceIn" class="inverted appear-animation bounceIn appear-animation-visible">
									<span class="word-rotate active" style="height: 54px;">
										<span class="word-rotate-items" style="top: -54px;">
											<span>success.</span>
											<span>advance.</span>
											<span>progress.</span>
										<span>success.</span></span>
									</span>
                </strong>
            </h2>
            <p class="featured lead">
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque rutrum pellentesque imperdiet. Nulla lacinia iaculis nulla non <span class="alternative-font">metus.</span> pulvinar. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Ut eu risus enim, ut pulvinar lectus. Sed hendrerit nibh.
            </p>
        </div>
    </div>

    <hr class="tall">
</div>

<div class="container">

    <div class="row">
        <div class="col-md-12">
            <div class="row">
                <div class="col-md-4">
                    <div class="feature-box secundary">
                        <div class="feature-box-icon">
                            <i class="icon icon-group"></i>
                        </div>
                        <div class="feature-box-info">
                            <h4 class="shorter">Customer Support</h4>
                            <p class="tall">Lorem ipsum dolor sit amet, consectetur adipiscing <span class="alternative-font">metus.</span> elit. Quisque rutrum pellentesque imperdiet.</p>
                        </div>
                    </div>
                    <div class="feature-box secundary">
                        <div class="feature-box-icon">
                            <i class="icon icon-file"></i>
                        </div>
                        <div class="feature-box-info">
                            <h4 class="shorter">HTML5 / CSS3 / JS</h4>
                            <p class="tall">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque rutrum pellentesque imperdiet. Nulla lacinia iaculis nulla.</p>
                        </div>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="feature-box secundary">
                        <div class="feature-box-icon">
                            <i class="icon icon-film"></i>
                        </div>
                        <div class="feature-box-info">
                            <h4 class="shorter">Sliders</h4>
                            <p class="tall">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque rutrum pellentesque imperdiet. Nulla lacinia iaculis nulla.</p>
                        </div>
                    </div>
                    <div class="feature-box secundary">
                        <div class="feature-box-icon">
                            <i class="icon icon-check"></i>
                        </div>
                        <div class="feature-box-info">
                            <h4 class="shorter">Icons</h4>
                            <p class="tall">Lorem ipsum dolor sit amet, consectetur adipiscing <span class="alternative-font">metus.</span> elit. Quisque rutrum pellentesque imperdiet.</p>
                        </div>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="feature-box secundary">
                        <div class="feature-box-icon">
                            <i class="icon icon-bars"></i>
                        </div>
                        <div class="feature-box-info">
                            <h4 class="shorter">Buttons</h4>
                            <p class="tall">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque rutrum pellentesque imperdiet. Nulla lacinia iaculis nulla.</p>
                        </div>
                    </div>
                    <div class="feature-box secundary">
                        <div class="feature-box-icon">
                            <i class="icon icon-desktop"></i>
                        </div>
                        <div class="feature-box-info">
                            <h4 class="shorter">Lightbox</h4>
                            <p class="tall">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque rutrum pellentesque imperdiet. Nulla lacinia iaculis nulla.</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>

<section class="featured highlight footer">
    <div class="container">
        <div class="row center counters">
            <div class="col-md-3">
                <strong data-append="+" data-to="4000">0</strong>
                <label>Happy Clients</label>
            </div>
            <div class="col-md-3">
                <strong data-to="15">0</strong>
                <label>Years in Business</label>
            </div>
            <div class="col-md-3">
                <strong data-to="352">0</strong>
                <label>Cups of Coffee</label>
            </div>
            <div class="col-md-3">
                <strong data-to="159">0</strong>
                <label>High Score</label>
            </div>
        </div>
    </div>
</section>

<section style="background-image: url(&quot;img/parallax-transparent.jpg&quot;); background-position: 0px 0px;" data-stellar-background-ratio="0.5" class="parallax">
    <div class="container">
        <div class="row center">
            <div class="col-md-12">

                <div class="row">
                    <div data-plugin-options="{&quot;items&quot;: 1}" class="owl-carousel owl-theme owl-carousel-init" style="opacity: 1; display: block;">
                        <div class="owl-wrapper-outer"><div class="owl-wrapper" style="width: 7020px; left: 0px; display: block;"><div class="owl-item" style="width: 1170px;"><div>
                                        <blockquote>
                                            <p><i class="icon icon-quote-left"></i> Hello, I want to thank you for creating a great template and for the excellent and quick support and help that you have been providing to me as I begin to work with it.</p>
                                            <span>- Joe Doe</span>
                                        </blockquote>
                                    </div></div><div class="owl-item" style="width: 1170px;"><div>
                                        <blockquote>
                                            <p><i class="icon icon-quote-left"></i> Just want to say Okler RULES. Provide great tech service for each template and allows me to become more knowledgeable as a designer.</p>
                                            <span>- Edward Chelton</span>
                                        </blockquote>
                                    </div></div><div class="owl-item" style="width: 1170px;"><div>
                                        <blockquote>
                                            <p><i class="icon icon-quote-left"></i> Just came here to say a big thank you to the author of this template. It works amazingly well, the documentation is top-notch, and the theme looks beautiful.</p>
                                            <span>- Bruce Ericson</span>
                                        </blockquote>
                                    </div></div></div></div>


                        <div class="owl-controls clickable"><div class="owl-pagination"><div class="owl-page active"><span class=""></span></div><div class="owl-page"><span class=""></span></div><div class="owl-page"><span class=""></span></div></div></div></div>
                </div>

            </div>
        </div>
    </div>
</section>

<div class="container">
    <div class="row">
        <div class="col-md-5">
            <h2><strong>Who</strong> We Are</h2>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur pellentesque neque eget diam posuere porta. Quisque ut nulla at nunc <a href="#">vehicula</a> lacinia. Proin adipiscing porta tellus, ut feugiat nibh adipiscing sit amet. In eu justo a felis faucibus ornare vel id metus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; In eu libero ligula. </p>
        </div>
        <div class="col-md-7">
            <div class="progress-bars">
                <div class="progress-label">
                    <span>HTML/CSS</span>
                </div>
                <div class="progress">
                    <div data-appear-progress-animation="100%" class="progress-bar progress-bar-primary">
                        <span class="progress-bar-tooltip">100%</span>
                    </div>
                </div>
                <div class="progress-label">
                    <span>Design</span>
                </div>
                <div class="progress">
                    <div data-appear-animation-delay="300" data-appear-progress-animation="85%" class="progress-bar progress-bar-primary">
                        <span class="progress-bar-tooltip">85%</span>
                    </div>
                </div>
                <div class="progress-label">
                    <span>WordPress</span>
                </div>
                <div class="progress">
                    <div data-appear-animation-delay="600" data-appear-progress-animation="75%" class="progress-bar progress-bar-primary">
                        <span class="progress-bar-tooltip">75%</span>
                    </div>
                </div>
                <div class="progress-label">
                    <span>Photoshop</span>
                </div>
                <div class="progress">
                    <div data-appear-animation-delay="900" data-appear-progress-animation="85%" class="progress-bar progress-bar-primary">
                        <span class="progress-bar-tooltip">85%</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <hr class="tall">
</div>

<div class="container">
    <div id="team" class="row">
        <div class="col-md-12">

            <div class="row">

                <ul class="team-list">
                    <li class="col-md-3">
                        <div class="team-item thumbnail">
                            <a class="thumb-info team" href="about-me.html">
                                <img height="270" src="img/team/team-1.jpg" alt="">
												<span class="thumb-info-title">
													<span class="thumb-info-inner">John Doe</span>
													<span class="thumb-info-type">CEO</span>
												</span>
                            </a>
											<span class="thumb-info-caption">
												<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras ac ligula mi, non suscipitaccumsan.</p>
												<span class="thumb-info-social-icons">
													<a data-original-title="Facebook" href="http://www.facebook.com" target="_blank" data-placement="bottom" rel="tooltip"><i class="icon icon-facebook"></i><span>Facebook</span></a>
													<a data-original-title="Twitter" href="http://www.twitter.com" data-placement="bottom" rel="tooltip"><i class="icon icon-twitter"></i><span>Twitter</span></a>
													<a data-original-title="Linkedin" href="http://www.linkedin.com" data-placement="bottom" rel="tooltip"><i class="icon icon-linkedin"></i><span>Linkedin</span></a>
												</span>
											</span>
                        </div>
                    </li>
                    <li class="col-md-3">
                        <div class="team-item thumbnail">
                            <a class="thumb-info team" href="about-me.html">
                                <img height="270" src="img/team/team-2.jpg" alt="">
												<span class="thumb-info-title">
													<span class="thumb-info-inner">Jessica Doe</span>
													<span class="thumb-info-type">Marketing</span>
												</span>
                            </a>
											<span class="thumb-info-caption">
												<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras ac ligula mi, non suscipitaccumsan.</p>
												<span class="thumb-info-social-icons">
													<a data-original-title="Facebook" href="http://www.facebook.com" target="_blank" data-placement="bottom" rel="tooltip"><i class="icon icon-facebook"></i><span>Facebook</span></a>
													<a data-original-title="Twitter" href="http://www.twitter.com" data-placement="bottom" rel="tooltip"><i class="icon icon-twitter"></i><span>Twitter</span></a>
													<a data-original-title="Linkedin" href="http://www.linkedin.com" data-placement="bottom" rel="tooltip"><i class="icon icon-linkedin"></i><span>Linkedin</span></a>
												</span>
											</span>
                        </div>
                    </li>
                    <li class="col-md-3">
                        <div class="team-item thumbnail">
                            <a class="thumb-info team" href="about-me.html">
                                <img height="270" src="img/team/team-3.jpg" alt="">
												<span class="thumb-info-title">
													<span class="thumb-info-inner">Rick Edward Doe</span>
													<span class="thumb-info-type">Developer</span>
												</span>
                            </a>
											<span class="thumb-info-caption">
												<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras ac ligula mi, non suscipitaccumsan.</p>
												<span class="thumb-info-social-icons">
													<a data-original-title="Facebook" href="http://www.facebook.com" target="_blank" data-placement="bottom" rel="tooltip"><i class="icon icon-facebook"></i><span>Facebook</span></a>
													<a data-original-title="Twitter" href="http://www.twitter.com" data-placement="bottom" rel="tooltip"><i class="icon icon-twitter"></i><span>Twitter</span></a>
													<a data-original-title="Linkedin" href="http://www.linkedin.com" data-placement="bottom" rel="tooltip"><i class="icon icon-linkedin"></i><span>Linkedin</span></a>
												</span>
											</span>
                        </div>
                    </li>
                    <li class="col-md-3">
                        <div class="team-item thumbnail">
                            <a class="thumb-info team" href="about-me.html">
                                <img height="270" src="img/team/team-4.jpg" alt="">
												<span class="thumb-info-title">
													<span class="thumb-info-inner">Melinda Wolosky</span>
													<span class="thumb-info-type">Design</span>
												</span>
                            </a>
											<span class="thumb-info-caption">
												<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras ac ligula mi, non suscipitaccumsan.</p>
												<span class="thumb-info-social-icons">
													<a data-original-title="Facebook" href="http://www.facebook.com" target="_blank" data-placement="bottom" rel="tooltip"><i class="icon icon-facebook"></i><span>Facebook</span></a>
													<a data-original-title="Twitter" href="http://www.twitter.com" data-placement="bottom" rel="tooltip"><i class="icon icon-twitter"></i><span>Twitter</span></a>
													<a data-original-title="Linkedin" href="http://www.linkedin.com" data-placement="bottom" rel="tooltip"><i class="icon icon-linkedin"></i><span>Linkedin</span></a>
												</span>
											</span>
                        </div>
                    </li>
                </ul>

            </div>
        </div>
    </div>
</div>

<section class="call-to-action featured footer">
    <div class="container">
        <div class="row">
            <div class="center">
                <h3>Porto is <strong>everything</strong> you need to create an <strong>awesome</strong> website! <a data-appear-animation="bounceIn" class="btn btn-lg btn-primary appear-animation" target="_blank" href="http://themeforest.net/item/porto-responsive-html5-template/4106987">Buy Now!</a> <span style="top: -22px;" data-appear-animation="rotateInUpLeft" class="arrow hlb appear-animation"></span></h3>
            </div>
        </div>
    </div>
</section>

</div>