<footer id="footer">
    <div class="container">
        <div class="row">
            <div class="footer-ribon">
                <span>Get in Touch</span>
            </div>
            <div class="col-md-3">
                <div class="newsletter">


                    <style type="text/css">
                        #newsletterForm label.error{
                            position: absolute !important;
                            top:44px;
                            left:0px;
                            color: #ff514c;
                            font-size: 0.9em;

                            z-index: 10000;
                        }

                    </style>

                    <?php
                    if (isset($form)){
                    ?>
                    <h4>Newsletter</h4>
                    <p>Keep up on our always evolving product features and technology. Enter your e-mail and subscribe to our newsletter.</p>

                    <div class="alert alert-success hidden" id="newsletterSuccess">
                        <strong>Success!</strong> You've been added to our email list.
                    </div>

                    <div class="alert alert-danger hidden" id="newsletterError"></div>
                    <?php

                        $form->setAttribute('action', $this->url('newsletter', array('action' => 'add')));
                        $form->setAttribute('id','newsletterForm');
                        //$form->setAttribute('novalidate','novalidate');
                        $form->prepare();
                        echo $this->form()->openTag($form);
                        echo $this->formRow($form->get('remove'));
                            echo "<div class='input-group'>";
                                echo $this->formRow($form->get('email')->setAttribute('class','form-control')->setAttribute('label',''));

                                echo "<span class='input-group-btn'>";
                                    echo $this->formSubmit($form->get('submit')->setAttribute('class','btn btn-default'));
                                echo "</span>";

                            echo "</div>";

                        echo $this->form()->closeTag();
                    }
                    ?>

                </div>
            </div>
            <div class="col-md-3">
                <h4>Latest Tweet</h4>
                <div id="tweet" class="twitter" data-account-id="">
                    <p>Please wait...</p>
                </div>
            </div>
            <div class="col-md-4">
                <div class="contact-details">
                    <h4>Contact Us</h4>
                    <ul class="contact">
                        <li><p><i class="icon icon-map-marker"></i> <strong>Address:</strong> 1234 Street Name, City Name, United States</p></li>
                        <li><p><i class="icon icon-phone"></i> <strong>Phone:</strong> (123) 456-7890</p></li>
                        <li><p><i class="icon icon-envelope"></i> <strong>Email:</strong> <a href="mailto:mail@example.com">mail@example.com</a></p></li>
                    </ul>
                </div>
            </div>
            <div class="col-md-2">
                <h4>Follow Us</h4>
                <div class="social-icons">
                    <ul class="social-icons">
                        <li class="facebook"><a href="http://www.facebook.com/" target="_blank" data-placement="bottom" rel="tooltip" title="Facebook">Facebook</a></li>
                        <li class="twitter"><a href="http://www.twitter.com/" target="_blank" data-placement="bottom" rel="tooltip" title="Twitter">Twitter</a></li>
                        <li class="linkedin"><a href="http://www.linkedin.com/" target="_blank" data-placement="bottom" rel="tooltip" title="Linkedin">Linkedin</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="footer-copyright">
        <div class="container">
            <div class="row">
                <div class="col-md-1">
                    <a href="index.html" class="logo">
                        <img alt="Porto Website Template" class="img-responsive" src="img/logo-footer.png">
                    </a>
                </div>
                <div class="col-md-7">
                    <p>© Copyright 2014. All Rights Reserved.</p>
                </div>
                <div class="col-md-4">
                    <nav id="sub-menu">
                        <ul>
                            <li><a href="page-faq.html">FAQ's</a></li>
                            <li><a href="sitemap.html">Sitemap</a></li>
                            <li><a href="contact-us.html">Contact</a></li>
                        </ul>
                    </nav>
                </div>
            </div>
        </div>
    </div>
</footer>